import asyncio
import re
from playwright.async_api import Playwright, async_playwright, expect


async def run(playwright: Playwright) -> None:
    browser = await playwright.chromium.launch(headless=False)
    context = await browser.new_context()
    page = await context.new_page()
    await page.goto("https://health.gig-gulf.com/externalsso/ids/login?signin=686a9cfce07ba5d8341b1c0d29b32635")
    await page.get_by_role("textbox", name="Username").click()
    await page.get_by_role("textbox", name="Username").fill("IMEDICAL")
    await page.get_by_role("textbox", name="Password").click()
    await page.get_by_role("textbox", name="Password").fill("Interactive@2025")
    await page.get_by_role("button", name="Login").click()
    async with page.expect_popup() as page1_info:
        await page.get_by_role("link", name=" Add Broker Quotation").click()
    page1 = await page1_info.value
    await page1.get_by_role("button", name="Select Country   ").first.click()
    await page1.get_by_role("listbox").get_by_role("option", name="United Arab Emirates").click()
    await page1.locator("input[name=\"IApplicantFName\"]").click()
    await page1.locator("input[name=\"IApplicantFName\"]").fill("Kane")
    await page1.locator("input[name=\"IApplicantLName\"]").click()
    await page1.locator("input[name=\"IApplicantLName\"]").fill("Williamson")
    await page1.locator("#MindateBlock").click()
    await page1.get_by_role("cell", name="31").nth(1).click()
    await page1.locator("#MaxdateBlock").click()
    await page1.locator("#MaxdateBlock").fill("18/04/1998")
    await page1.get_by_role("button", name="Select Gender   ").click()
    await page1.get_by_role("listbox").get_by_role("option", name="Male", exact=True).click()
    await page1.get_by_role("button", name="Select Marital Status   ").click()
    await page1.get_by_role("listbox").get_by_role("option", name="Married").click()
    await page1.locator("#Imaskphone").click()
    await page1.get_by_role("button", name="Select Nationality   ").click()
    await page1.get_by_role("listbox").get_by_role("option", name="Indian").click()
    await page1.get_by_role("button", name="Select State   ").click()
    await page1.get_by_role("listbox").get_by_role("option", name="Abu Dhabi").click()
    await page1.get_by_role("button", name="Select Visa Location   ").click()
    await page1.get_by_role("listbox").get_by_role("option", name="Abu Dhabi").click()
    await page1.get_by_role("button", name="Select Country   ").click()
    await page1.get_by_role("listbox").get_by_role("option", name="India", exact=True).click()
    await page1.get_by_role("button", name="Select Work Location   ").click()
    await page1.get_by_role("listbox").get_by_role("option", name="AL KARAMA").click()
    await page1.get_by_role("button", name="Select Occupation   ").click()
    await page1.get_by_role("listbox").get_by_role("option", name="Accountant").click()
    await page1.get_by_role("textbox", name="john@gmail.com").click()
    await page1.get_by_role("textbox", name="john@gmail.com").fill("kanetest@gmail.com")
    await page1.get_by_role("button", name="Select   ").click()
    await page1.get_by_role("listbox").get_by_role("option", name=">4000 and <=12000 AED/month").click()
    await page1.get_by_role("spinbutton").click()
    await page1.get_by_role("spinbutton").click()
    await page1.get_by_role("spinbutton").fill("2")
    await page1.get_by_role("button", name="All   ").click()
    await page1.get_by_role("listbox").get_by_role("option", name="All").click()
    await page1.get_by_role("button", name="Select Visa Type   ").click()
    await page1.get_by_role("listbox").get_by_role("option", name="Resident visa").click()
    await page1.get_by_role("link", name="Next").click()
    await page1.locator("#DependentRow0").get_by_role("button", name="Select Title   ").click()
    await page1.get_by_role("listbox").get_by_role("option", name="MS").click()
    await page1.get_by_role("row", name="MS    MS Select Gender   ").locator("input[name=\"DFullName\"]").click()
    await page1.get_by_role("row", name="MS    MS Select Gender   ").locator("input[name=\"DFullName\"]").fill("Alexandra Kane")
    await page1.get_by_role("row", name="MS    MS Alexandra Kane").get_by_placeholder("DD/MM/YYYY").click()
    await page1.get_by_role("row", name="MS    MS Alexandra Kane").get_by_placeholder("DD/MM/YYYY").fill("26/08/1998")
    await page1.locator("#DependentRow0").get_by_role("button", name="Select Gender   ").click()
    await page1.get_by_role("listbox").get_by_role("option", name="Female").click()
    await page1.locator("#DependentRow0").get_by_role("button", name="Select Relation   ").click()
    await page1.get_by_role("listbox").get_by_role("option", name="Wife").click()
    await page1.locator("#DependentRow0").get_by_role("button", name="Select Marital Status   ").click()
    await page1.get_by_role("listbox").get_by_role("option", name="Married").click()
    await page1.locator("#DependentRow0").get_by_role("button", name="Select Nationality   ").click()
    await page1.get_by_role("listbox").get_by_role("option", name="Indian").click()
    await page1.get_by_role("button", name="Select Title   ").click()
    await page1.get_by_role("listbox").get_by_role("option", name="MR").click()
    await page1.get_by_role("row", name="MR    MR Select Gender   ").locator("input[name=\"DFullName\"]").click()
    await page1.get_by_role("row", name="MR    MR Select Gender   ").locator("input[name=\"DFullName\"]").fill("Ravindra Kane")
    await page1.get_by_role("row", name="MR    MR Ravindra Kane").get_by_placeholder("DD/MM/YYYY").click()
    await page1.get_by_role("row", name="MR    MR Ravindra Kane").get_by_placeholder("DD/MM/YYYY").fill("13/06/2023")
    await page1.get_by_role("button", name="Select Gender   ").click()
    await page1.get_by_role("listbox").get_by_role("option", name="Male", exact=True).click()
    await page1.get_by_role("button", name="Select Relation   ").click()
    await page1.get_by_role("listbox").get_by_role("option", name="Son").click()
    await page1.get_by_role("button", name="Select Marital Status   ").click()
    await page1.get_by_role("listbox").get_by_role("option", name="Single").click()
    await page1.get_by_role("button", name="Select Nationality   ").click()
    await page1.get_by_role("listbox").get_by_role("option", name="Indian").click()
    await page1.get_by_role("link", name="Next").click()

    # ---------------------
    await context.close()
    await browser.close()


async def main() -> None:
    async with async_playwright() as playwright:
        await run(playwright)


asyncio.run(main())
